# Utiliza uma imagem base oficial do Node.js
FROM node:20

# Instala o PostgreSQL
RUN apt-get update && \
    apt-get install -y postgresql postgresql-contrib && \
    rm -rf /var/lib/apt/lists/*

# Define o diretório de trabalho no contêiner
WORKDIR /usr/src/app

# Copia os arquivos de package.json e package-lock.json
COPY package*.json ./

# Instala as dependências do Node.js
RUN npm install

# Copia o restante do código da aplicação
COPY . .

# Copia o script SQL de inicialização para o diretório apropriado
COPY init.sql /docker-entrypoint-initdb.d/

# Porta que a aplicação vai expor
EXPOSE 3000

# Define variáveis de ambiente para o PostgreSQL
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=123456
ENV POSTGRES_DB=postgres

# Script de inicialização que inicia o PostgreSQL e a aplicação Node.js
COPY entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]